cdflib/cdfread.py

It looks like a block needed to be indented one more level, to go under the `with self.file.open('rb') as f` statement.

Fix vxrs2 file reading

---

cdflib/cdfread.py

This needed a `with...` block like all the other code surrounding it.

Fix _read_aedr2

---

cdflib/cdfread.py

Only set 'WRITABLE' if possible

---

cdflib/cdfread.py

Refactor _read_adr into a single method

---

cdflib/epochs.py
tests/test_epochs.py

Recently found that this funciton was a massive bottleneck for my code, because it isn't vectorised. This PR starts the process of massively speeding it up by doing everything with arrays.
Current speedup: ~10x

Speed up breakdown_tt2000

---

cdflib/epochs.py

Gives an ~15x speedup on processing dates.

Vectorize _LeapSecondsfromJ2000

---

tests/test_epochs.py

Update range of valid TT2000 times in tests

---

cdflib/epochs.py
tests/test_epochs.py

Fixes https://github.com/MAVENSDC/cdflib/issues/96.

Add tzinfo to utc timestamp

---

.github/workflows/conda-build.yaml
.travis.yml
README.md
cdflib/cdfread.py
cdflib/cdfwrite.py
cdflib/epochs.py
doc/conf.py
setup.cfg
tests/test_astropy_epochs.py
tests/test_cdfwrite.py
tests/test_epochs.py
tox.ini

Fixes #87.
Also upgrade Python syntax with https://github.com/asottile/pyupgrade using `--py36-plus`.

Drop support for Python 3.5

---

cdflib/cdfread.py

Fixes https://github.com/MAVENSDC/cdflib/issues/95. Not sure how to test for this...

Explicitly close temporary files

---

cdflib/epochs.py

Small change to reduce redundant code.

Refactor breakdown

---

cdflib/epochs.py

This speeds up `to_datetime` by ~6x for me locally.

Vectorise to_datetime

---

.github/workflows/ci.yml
.travis.yml
pytest.ini
setup.cfg

This is more widely used, and I personally think a better tool for looking at code coverage.

Use codecov for coverage

---

cdflib/cdfread.py

This is the pythonic way to avoid `self`.

Use @staticmethod in cdfread

---

cdflib/cdfread.py
tests/test_cdfread.py

Fixes https://github.com/MAVENSDC/cdflib/issues/125. This results in a factor of ~2x speed up when reading a whole CDF file with sunpy.

Keep CDF file open while CDF object is alive

---

cdflib/cdf_to_xarray.py
doc/modules/xarray.rst

This is breaking sunpy CI, but making xarray optional should fix it

Make xarray an optional dependency

---

cdflib/__init__.py
cdflib/cdfread.py
cdflib/cdfwrite.py
cdflib/logging.py
cdflib/s3.py
cdflib/xarray/cdf_to_xarray.py
cdflib/xarray/xarray_to_cdf.py
doc/changelog.rst

Eventually fixes https://github.com/MAVENSDC/cdflib/issues/40.
Fixes https://github.com/MAVENSDC/cdflib/issues/216

Use logger intstead of print statements

---

cdflib/cdfread.py

Fixes https://github.com/MAVENSDC/cdflib/issues/220

Fix cdf_info() docs

---

cdflib/cdfread.py
doc/changelog.rst
tests/test_cdfread.py

Fixes https://github.com/MAVENSDC/cdflib/issues/226

Fix reading globalatts with multiple entries

---

cdflib/cdfwrite.py
cdflib/xarray/cdf_to_xarray.py
cdflib/xarray/xarray_to_cdf.py
tests/test_xarray_reader_writer.py

"Epoch" must be monotonically increasing to be ISTP compliant

Add a check for Epoch being monotonically increasing in xarray_to_cdf

---

cdflib/cdfwrite.py
cdflib/epochs.py

Also added an __init__.py to the test, and fixed a debug statement

Using x.ndim > 0 rather than hasattr(x, "__len__")

---

.github/workflows/ci.yml
cdflib/xarray/xarray_to_cdf.py
setup.cfg

* Consolidate the regex calls
* Add netcdf4 to the test dependencies

consolidate regex calls / add netcdf4 to test deps

---

setup.cfg

Don't catchall, set cdflib explicitly.
Fixes #273

Only install cdflib package
