MAVENSDC/cdflib

cdflib/cdf.py, cdflib/epochs.py
The None comparisons are changed to use the recommended "is" and "is not" idiom as per PEP8. See http://legacy.python.org/dev/peps/pep-0008/#programming-recommendations
=> Fix none comparisons

cdflib/__init__.py
Currently, doing
```python
import cdflib
cdflib.CDF('~/sample.cdf')
```
won't read the file, because `os.path.exists()` isn't `True`; this just expands the path if there is a `~` in it, so the file is correctly read.
=> Expand user path when reading CDF

.gitignore
This is just a directory with cached dependencies for `setuptools`
=> Ignore .eggs directory

MANIFEST.in, cdflib/epochs.py, tests/test_epochs.py
Alternative to  #47 - just include the latest leapseconds table, and have a test to check it's the most recent one.
=> Hard code leapseconds table

cdflib/cdfread.py
Instead of printing a message, this raises proper errors when a user provided input is not valid.
=> Raise errors where appropriate in cdfread

.appveyor.yml, .coveragerc, .travis.yml, cdflib/cdfread.py, cdflib/epochs.py, pytest.ini, setup.cfg, tests/test_cdfwrite.py
other major libraries like NetCDF4 and h5py use simple numpy-like read indexing like:
```python
with h5py.File('my.h5') as f:
x = f["x"]
```
this PR bring that easy indexing users expect to cdflib:
```python
h = cdfread.CDF('my.cdf')
x = h["x"]
```
That is done by the `__getitem__` in cdfread.py
Separately, I cleaned up:
* read/write functions in tests/test_cdfwrite.py, allowing backward compatibility to Python 3.5, and which would be required as well for Python 2.7 if that is implemented someday.
* corrected raw-string for regex, which is needed for Python &ge; 3.7
I have been having to run my own fork of CDFlib, and these changes would allow me to direct my users to this main CDFlib instead. thanks.
As we discussed at AGU,  I have made other performance and API improvements, but I'll do …
=> Numpy-like index on read

.flake8, cdflib/__init__.py, cdflib/cdfread.py, cdflib/epochs.py, setup.cfg, tests/test_epochs.py
following on from #38, these changes are the other half of what my forked cdflib users need.
* datetime.datetime output option via `to_datetime()`
* Python intrinsic exceptions `raise TypeError()` `raise KeyError()` etc. instead of `return None`, as the latter breaks essential Python syntax
So consider first merging the approved #38, then this PR.
happy to discuss.
=> datetime.datetime output, raise Error instead of return None

.flake8, cdflib/__init__.py, cdflib/cdfread.py, cdflib/epochs.py, setup.cfg, tests/test_epochs.py
* added `to_datetime()` method, this is the key thing keeping my fork of cdflib open. I can close it after this is merged
* updated use of `isinstance()` to compact clean format
* pep8 style
* correct logic for iso8601 argument default behavior
* cleanup unused `unittest`
=> add to_datetime method, cleanup PEP8 style

cdflib/cdfread.py
There are checks earlier in the function that raise an error if the requested variable doesn't exist, but it seems reasonable (and necessary in some cases) to not fail if the variable exists but doesn't have any data.
=> Don't fail if variable exists but has no data

.appveyor.yml, .github/workflows/ci.yml, .travis.yml, README.md, archive/.appveyor.yml, cdflib/__init__.py, cdflib/cdfwrite.py, cdflib/epochs.py, cdflib/epochs_astropy.py, mypy.ini, pyproject.toml, pytest.ini, setup.cfg, tests/test_astropy_epochs.py, tests/test_cdfread.py, tests/test_cdfwrite.py, tests/test_epochs.py
* it appears appveyor isn't used anymore, and appveyor had lots of errors when I enabled it, so move appveyor.yml to archive. 
* added GitHub Actions to replace Appveyor (more stable, faster, more features)
* added Python 3.8 to CI
* use pytest.ini instead of duplicating options everywhere
* in general, tests that require downloads can falsely fail on CI, so catch download failures with skip message
* added `@staticmethod` decorator to non-self class methods
* fixed numerous PEP8 issues, including bare `except:` that harm stability
* use pyproject.toml instead of setup_requires so that offline installs work and it's generally the current way to do this
=> code / install / ci quality 

cdflib/epochs.py
Currently to use `CDFepoch.to_datetime` one has to create an instance of `CDFepoch`. This is because the method uses `self` to access the static method `breakdown` of `CDFepoch`, which is unnecessary.
`to_datetime` could be static as well, and access `breakdown` via `CDFepoch.breakdown` (since it is static), but I decided to rather convert it to a `classmethod`, which still allows it to be called statically, but does not break compatibility with previous code, i.e. it can still be called on a `CDFepoch` instance as before, combining both approaches.
=> Convert CDFepoch.to_datetime to a classmethod

cdflib/epochs.py
The issue is 
`datetime.datetime(*date).replace(tzinfo=datetime.timezone.utc).timestamp()`
This will give different timestamp values (normally off by full hours) depending on the local time zone settings. This effect cannot be seen if your computers timezone is set to GMT.
This can be easily reproduced using:
`import datetime`
`print(datetime.datetime(2020, 1, 1).timestamp())`
`print(datetime.datetime(2020, 1, 1).replace(tzinfo=datetime.timezone.utc).timestamp())`
(when timezone is not set to GMT)
=> CDFepoch.unixtime returns incorrect timestamp values due to timezone issues

setup.cfg
The Travis CI build is failing for me:
```
@attr.s(slots=True, eq=False)
TypeError: attrs() got an unexpected keyword argument 'eq'
```
https://travis-ci.com/github/hugovk/cdflib/jobs/370622148
That's because `eq` isn't in old attrs:
> New in version 19.2.0: eq and order
https://www.attrs.org/en/stable/api.html#attr.s
=> Require attrs 19.2.0 to use eq in attr.s

.travis.yml
Python 3.9 is in beta with the final 3.9.0 release due in October. The CPython team recommended third-party libraries test against the beta and RCs.
=> Travis CI: Test on Python 3.9-dev

cdflib/cdfread.py
Makes the lack of data much clearer compared to returning `None`.
=> Raise error when no data present

cdflib/cdfread.py
A typo that makes reading older CDF files fail.
This change hopefully shouldn't break anything.
=> cdfread.py typo

.github/workflows/ci.yml, .gitignore, cdflib/cdfread.py, tests/test_cdfread.py
Addressing issue #115 
the _convert_np_data function in the CDF object was a NoSelf function, however in an update in 0.3.20 a reference to self was added. I have attempted to fix this issue, but I'm not sure if all of the changes made are acceptable.
OS: Windows 10 with WSL debian 10
Python version: 3.8
tests: pytest with flake8
=> updated cdfread to use self in functions that call it

.gitignore, cdflib/cdfread.py, cdflib/epochs.py
This pull request primarily simplifies the `breakdown_epoch` and `breakdown_epoch16` methods by pulling out the julian-to-date-and-time calculation common to both and placing it in a new method.  It also uses `np.asarray` to allow future mutli-dimensional input without breaking things.
Other changes include:
- updating `.gitignore` to ignore file created by running unit tests regardless of the directory that the tests were run in, and
- updating some docstring flanking quotes.
- adding some missing docstrings.
Unit tests pass locally (Mac OS X Mojave, python 3.7).
=> Simplify epoch calculation code

.readthedocs.yml
Turns out 3.9 isn't supported yet...
=> Use python 3.8 for RTD build

.readthedocs.yml, requirements/docs.txt
This was out of sync with the requirements in `setup.cfg`, so might as well remove.
=> Remove old requirements file

cdflib/cdfread.py
Fix for crashes with some (RBSP and ERG) CDFs that include non-ASCII characters:
https://github.com/spedas/pyspedas/issues/86
=> Now ignoring errors that occur while decoding the bytearray

cdflib/cdfread.py
according to CDFInternal Format Description  (https://spdf.gsfc.nasa.gov/pub/software/cdf/doc/cdf381/cdf38ifd.pdf), the size (cSize) of Compressed Variable Values Record (cvvr) is a 8bytes Int (16-24, which should be 8-16 here)
=> fix compressed_size offset(and size)

CHANGELOG.rst, README.md, cdflib/cdfread.py, cdflib/cdfwrite.py, cdflib/epochs.py, cdflib/epochs_astropy.py, doc/modules/cdfepoch.rst, doc/modules/cdfread.rst, doc/modules/cdfwrite.rst
This code all seems redundant and an extra maintenance burden - the user can just get the version from class attributes.
=> Remove getVersion()

cdflib/cdfwrite.py
When writing a CDF, the documentation states that a user can include a Majority value in the cdf_spec dictionary to specify if the data is row or column major. It seems like this value was never being read in the code, so I have corrected this.
=> Now uses Majority from cdf_spec when writing new CDFs

cdflib/cdfread.py, cdflib/cdfwrite.py, cdflib/gzip_wrapper.py
This PR allows to use deflate package when available. It could be added later a either dependency or optional dependency.
Here are some speedup examples:
Without libdeflate:
```
In [12]: %timeit cdflib.CDF("/home/jeandet/Downloads/bigcdf_compressed.cdf").varget("temp")
5.35 s ± 33.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [13]: %timeit cdflib.CDF("/home/jeandet/cdf_benchmarks/solo_l3_rpw-bia-efield_20220906_v01.cdf").varget("EDC_SRF")
786 ms ± 5.26 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
With libdeflate:
```
In [8]: %timeit cdflib.CDF("/home/jeandet/Downloads/bigcdf_compressed.cdf").varget("temp")
1.19 s ± 23.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
In [9]: %timeit cdflib.CDF("/home/jeandet/cdf_benchmarks/solo_l3_rpw-bia-efield_20220906_v01 …
```
=> Adds automatic support for libdeflate which yields at least a 2x speedup

cdflib/xarray/cdf_to_xarray.py
I was briefly confused about whether the `cdf_to_xarray` function was under `cdflib.xarray`, as implied by the [definition in the API docs](https://cdflib.readthedocs.io/en/latest/api/cdflib.xarray.cdf_to_xarray.html#cdf-to-xarray) or `cdflib` itself, as implied by the docstring.
This PR corrects the docs to import `cdflib.xarray` and use `cdflib.xarray.cdf_to_xarray`, which should be correct as of [version 1.0.1](https://cdflib.readthedocs.io/en/stable/changelog.html#id9).
=> Change `cdflib.cdf_to_xarray` to `cdflib.xarray.cdf_to_xarray` in docstring

cdflib/cdfwrite.py
Remove the bool(all(obj)) check in the _checkListofNums() method.
Now it will correctly return 'True' if passed an list like [22, 5, 0] Before, it would fail because the 0 evaluated to False
Closes issue #235
=> Update cdfwrite.py to correct false negative

cdflib/xarray/cdf_to_xarray.py, cdflib/xarray/xarray_to_cdf.py
* Attributes that are given a datetime64 or datetime object are automatically converted to a cdf time in xarray_to_cdf
* Attributes that have the data type EPOCH/EPOCH16/TT2000 in a CDF file are put into an attribute list "TIME_ATTRS" in cdf_to_xarray
* Attributes that are in the attribute "TIME_ATTRS" are automatically converted to a cdf time in xarray_to_cdf
=> Auto convert attribute times

cdflib/cdfwrite.py, tests/test_cdfwrite.py
I encountered an unclear error message when using cdflib, so this PR is to suggest a new wording that makes it clear to the end user what is going on. 
It is possible that this should not even throw an error, and that the use case is valid, in which case I can add a new path in _convert_data to accommodate it. There is an existing path for CDF_CHAR data types, but only if the input is a list type, which in my case it was not. 
I also think this is not a good error message and would appreciate suggestions for rewording. 
I also reformatted the test file, the only changes I made are the new test at the bottom. Let me know if you'd prefer I remove the reformatted pieces.
I also added a test to demonstrate the issue, but I also have reproducible code: 
```
test_attrs = {'Project': …
```
=> Update cdfwrite to include a more intelligent error message

.github/workflows/ci.yml, cdflib/cdfread.py, setup.cfg, tox.ini
This fixes #243 
Firstly, apologies for the slight yak shaving expedition I did into refactoring your CI. I have moved your CI config over to use tox and the [OpenAstronomy tox reuseable workflow](https://github.com/OpenAstronomy/github-actions-workflows). I am happy to either revert this if you don't like it, or to double down and also migrate your publish workflow to use it as well!
The reason I did this is to add a CI build which installs the development wheels of numpy and astropy to test against upcoming changes in those libraries. I also configured a build which uses `--remote-data` with the `-online` tox factor.
=> Fix compatibility with numpy 2.0 (and add devdeps tests to CI)

cdflib/cdfread.py
Modified 'cdfread' in the part for reading from AWS S3 to allow anonymous access for datasets such as NASA TOPS.  If users do not have an AWS access, the try/except then re-fetches the data using the anonymous/unsigned.  Tested on HelioCloud's public 2PB data store at s3://gov-nasa-hdrl-data1/, also useful for people with their own S3 datasets.  Does not affect nor break any non-S3 functionality.
=> Updated AWS reads to allow anon access for datasets such as NASA TOPS
